import type { Metadata } from "next";
import "./globals.css";

import { Inter, Noto_Sans_JP } from 'next/font/google'
import SectionMargin from "@/features/top/components/SectionMargin";
import Header from "@/features/common/components/Header";
import Footer from "@/features/common/components/Footer";

export const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap',
})

export const notoSansJP = Noto_Sans_JP({
    subsets: ['latin'],
    variable: '--font-noto-sans-jp',
    display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${inter.variable} ${notoSansJP.variable} antialiased`}
      >
        <SectionMargin />
        <Header subText={"SampletextSampletextSampletextSampletextSamplete"}>
          Waratake Blog
        </Header>
        <SectionMargin />
        {children}
        <SectionMargin />
        <Footer />
      </body>
    </html>
  );
}
